### ISSUE TITLE
Failed to install on Windows 10

### ISSUE THREAD

**Issue by prashanthmadi** [2Toad/node-teradata#25]
Anyone installed successfully on windows 10 ?
```
npm install --arch=ia32 node-Teradata
```
I got below error

java.obj : error LNK2001: unresolved external symbol __imp__JNI_CreateJavaVM@12 [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavabridge_bindin gs.vcxproj] C:\Workspace\nodejs\rest\node_modules\java\build\Release\nodejavabridge_bindings.node : fatal error LNK1120: 1 unresolved externals [C:\Workspace\nodej s\rest\node_modules\java\build\nodejavabridge_bindings.vcxproj]

```

C:\Workspace\nodejs\rest>npm install --arch=ia32 node-teradata
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> java@0.8.0 install C:\Workspace\nodejs\rest\node_modules\java
> node-gyp rebuild


C:\Workspace\nodejs\rest\node_modules\java>if not defined npm_config_node_gyp (node "C:\Users\prmadi\AppData\Roaming\nvm\v6.9.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  java.cpp
  javaObject.cpp
  javaScope.cpp
  methodCallBaton.cpp
  nodeJavaBridge.cpp
  utils.cpp
  win_delay_load_hook.cc
..\src\javaObject.cpp(116): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodej
avabridge_bindings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(3274): note: see declaration of 'v8::Function::NewInstance'
..\src\javaObject.cpp(349): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodej
avabridge_bindings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(3274): note: see declaration of 'v8::Function::NewInstance'
..\src\utils.cpp(347): warning C4996: 'v8::Value::ToInt32': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavabridge_bi
ndings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(8202): note: see declaration of 'v8::Value::ToInt32'
..\src\utils.cpp(354): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavabridge_b
indings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(8166): note: see declaration of 'v8::Value::ToNumber'
..\src\java.cpp(897): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavabridge_bi
ndings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(8166): note: see declaration of 'v8::Value::ToNumber'
..\src\java.cpp(927): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavabridge_bi
ndings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(8166): note: see declaration of 'v8::Value::ToNumber'
..\src\java.cpp(956): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavabridge_bi
ndings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(8166): note: see declaration of 'v8::Value::ToNumber'
..\src\java.cpp(983): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavabridge_bi
ndings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(8166): note: see declaration of 'v8::Value::ToNumber'
..\src\java.cpp(1019): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavabridge_b
indings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(8166): note: see declaration of 'v8::Value::ToNumber'
..\src\java.cpp(1044): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavabridge_b
indings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(8166): note: see declaration of 'v8::Value::ToNumber'
..\src\utils.cpp(969): warning C4996: 'v8::Object::GetHiddenValue': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavab
ridge_bindings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(2956): note: see declaration of 'v8::Object::GetHiddenValue'
..\src\utils.cpp(973): warning C4996: 'v8::Object::SetHiddenValue': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavab
ridge_bindings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(2954): note: see declaration of 'v8::Object::SetHiddenValue'
..\src\utils.cpp(977): warning C4996: 'v8::Object::SetHiddenValue': was declared deprecated [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavab
ridge_bindings.vcxproj]
  C:\Users\prmadi\.node-gyp\6.9.1\include\node\v8.h(2954): note: see declaration of 'v8::Object::SetHiddenValue'
     Creating library C:\Workspace\nodejs\rest\node_modules\java\build\Release\nodejavabridge_bindings.lib and object C:\Workspace\nodejs\rest\node_mod
  ules\java\build\Release\nodejavabridge_bindings.exp
java.obj : error LNK2001: unresolved external symbol __imp__JNI_CreateJavaVM@12 [C:\Workspace\nodejs\rest\node_modules\java\build\nodejavabridge_bindin
gs.vcxproj]
C:\Workspace\nodejs\rest\node_modules\java\build\Release\nodejavabridge_bindings.node : fatal error LNK1120: 1 unresolved externals [C:\Workspace\nodej
s\rest\node_modules\java\build\nodejavabridge_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\prmadi\AppData\Roaming\nvm\v6.9.1\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\prmadi\\AppData\\Roaming\\nvm\\v6.9.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Workspace\nodejs\rest\node_modules\java
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

```

**Comment by azimshaik** [comment]
@prashanthmadi  Were you able to fix this  ?

**Comment by prashanthmadi** [comment]
nope

**Comment by azimshaik** [comment]
@prashanthmadi  I was wondering if this was because of any proxy ?

**Comment by jameswang2015** [comment]
I get error when installing this in my pc, the error is not exactly same as this one, so I will create a new issue to show and ask for help.
